// Polish powiat / city registration plate codes — extracted from uploads/index.html
// Each: { kod, nazwa, typ ('miasto'|'ziemski'), woj, lat, lng, wiki }
window.POWIATY = [
      // ========== DOLNOŚLĄSKIE (D) ==========
      { kod: "DB", nazwa: "Wałbrzych", typ: "miasto", woj: "dolnośląskie", lat: 50.7841, lng: 16.2845, wiki: "Wałbrzych" },
      { kod: "DJ", nazwa: "Jelenia Góra", typ: "miasto", woj: "dolnośląskie", lat: 50.9044, lng: 15.7195, wiki: "Jelenia_Góra" },
      { kod: "DL", nazwa: "Legnica", typ: "miasto", woj: "dolnośląskie", lat: 51.2070, lng: 16.1553, wiki: "Legnica" },
      { kod: "DW", nazwa: "Wrocław", typ: "miasto", woj: "dolnośląskie", lat: 51.1079, lng: 17.0385, wiki: "Wrocław" },
      { kod: "DBL", nazwa: "Bolesławiec", typ: "ziemski", woj: "dolnośląskie", lat: 51.2615, lng: 15.5697, wiki: "Bolesławiec" },
      { kod: "DDZ", nazwa: "Dzierżoniów", typ: "ziemski", woj: "dolnośląskie", lat: 50.7290, lng: 16.6510, wiki: "Dzierżoniów" },
      { kod: "DGL", nazwa: "Głogów", typ: "ziemski", woj: "dolnośląskie", lat: 51.6566, lng: 16.0848, wiki: "Głogów" },
      { kod: "DGR", nazwa: "Góra", typ: "ziemski", woj: "dolnośląskie", lat: 51.6720, lng: 16.5500, wiki: "Góra_(województwo_dolnośląskie)" },
      { kod: "DJA", nazwa: "Jawor", typ: "ziemski", woj: "dolnośląskie", lat: 51.0510, lng: 16.1932, wiki: "Jawor" },
      { kod: "DJE", nazwa: "Karkonoski", typ: "ziemski", woj: "dolnośląskie", lat: 50.8500, lng: 15.7667, wiki: "Powiat_karkonoski" },
      { kod: "DKA", nazwa: "Kamienna Góra", typ: "ziemski", woj: "dolnośląskie", lat: 50.7857, lng: 16.0297, wiki: "Kamienna_Góra" },
      { kod: "DKL", nazwa: "Kłodzko", typ: "ziemski", woj: "dolnośląskie", lat: 50.4356, lng: 16.6611, wiki: "Kłodzko" },
      { kod: "DLB", nazwa: "Lubań", typ: "ziemski", woj: "dolnośląskie", lat: 51.1208, lng: 15.2920, wiki: "Lubań_(województwo_dolnośląskie)" },
      { kod: "DLE", nazwa: "Legnica (powiat)", typ: "ziemski", woj: "dolnośląskie", lat: 51.1900, lng: 16.0500, wiki: "Powiat_legnicki" },
      { kod: "DLU", nazwa: "Lubin", typ: "ziemski", woj: "dolnośląskie", lat: 51.4015, lng: 16.2018, wiki: "Lubin" },
      { kod: "DLW", nazwa: "Lwówek Śląski", typ: "ziemski", woj: "dolnośląskie", lat: 51.1083, lng: 15.5806, wiki: "Lwówek_Śląski" },
      { kod: "DMI", nazwa: "Milicz", typ: "ziemski", woj: "dolnośląskie", lat: 51.5275, lng: 17.2769, wiki: "Milicz" },
      { kod: "DOA", nazwa: "Oława", typ: "ziemski", woj: "dolnośląskie", lat: 50.9462, lng: 17.2937, wiki: "Oława" },
      { kod: "DOL", nazwa: "Oleśnica", typ: "ziemski", woj: "dolnośląskie", lat: 51.2103, lng: 17.3893, wiki: "Oleśnica" },
      { kod: "DPL", nazwa: "Polkowice", typ: "ziemski", woj: "dolnośląskie", lat: 51.5050, lng: 16.0750, wiki: "Polkowice" },
      { kod: "DSR", nazwa: "Środa Śląska", typ: "ziemski", woj: "dolnośląskie", lat: 51.1697, lng: 16.5961, wiki: "Środa_Śląska" },
      { kod: "DST", nazwa: "Strzelin", typ: "ziemski", woj: "dolnośląskie", lat: 50.7800, lng: 17.0633, wiki: "Strzelin" },
      { kod: "DSW", nazwa: "Świdnica", typ: "ziemski", woj: "dolnośląskie", lat: 50.8434, lng: 16.4892, wiki: "Świdnica" },
      { kod: "DTR", nazwa: "Trzebnica", typ: "ziemski", woj: "dolnośląskie", lat: 51.3107, lng: 17.0633, wiki: "Trzebnica" },
      { kod: "DBA", nazwa: "Wałbrzych (powiat)", typ: "ziemski", woj: "dolnośląskie", lat: 50.8000, lng: 16.3000, wiki: "Powiat_wałbrzyski" },
      { kod: "DWL", nazwa: "Wołów", typ: "ziemski", woj: "dolnośląskie", lat: 51.3375, lng: 16.6442, wiki: "Wołów" },
      { kod: "DWR", nazwa: "Wrocław (powiat)", typ: "ziemski", woj: "dolnośląskie", lat: 51.1500, lng: 17.0500, wiki: "Powiat_wrocławski" },
      { kod: "DZA", nazwa: "Ząbkowice Śląskie", typ: "ziemski", woj: "dolnośląskie", lat: 50.5839, lng: 16.8128, wiki: "Ząbkowice_Śląskie" },
      { kod: "DZG", nazwa: "Zgorzelec", typ: "ziemski", woj: "dolnośląskie", lat: 51.1500, lng: 15.0000, wiki: "Zgorzelec" },
      { kod: "DZL", nazwa: "Złotoryja", typ: "ziemski", woj: "dolnośląskie", lat: 51.1262, lng: 15.7714, wiki: "Złotoryja" },

      // ========== KUJAWSKO-POMORSKIE (C) ==========
      { kod: "CB", nazwa: "Bydgoszcz", typ: "miasto", woj: "kujawsko-pomorskie", lat: 53.1235, lng: 18.0084, wiki: "Bydgoszcz" },
      { kod: "CG", nazwa: "Grudziądz", typ: "miasto", woj: "kujawsko-pomorskie", lat: 53.4844, lng: 18.7536, wiki: "Grudziądz" },
      { kod: "CT", nazwa: "Toruń", typ: "miasto", woj: "kujawsko-pomorskie", lat: 53.0138, lng: 18.5984, wiki: "Toruń" },
      { kod: "CW", nazwa: "Włocławek", typ: "miasto", woj: "kujawsko-pomorskie", lat: 52.6483, lng: 19.0677, wiki: "Włocławek" },
      { kod: "CAL", nazwa: "Aleksandrów Kujawski", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.8800, lng: 18.6900, wiki: "Aleksandrów_Kujawski" },
      { kod: "CBR", nazwa: "Brodnica", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.2580, lng: 19.3964, wiki: "Brodnica" },
      { kod: "CBY", nazwa: "Bydgoszcz (powiat)", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.1500, lng: 18.0000, wiki: "Powiat_bydgoski" },
      { kod: "CCH", nazwa: "Chełmno", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.3475, lng: 18.4242, wiki: "Chełmno" },
      { kod: "CGD", nazwa: "Golub-Dobrzyń", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.1117, lng: 19.0526, wiki: "Golub-Dobrzyń" },
      { kod: "CGR", nazwa: "Grudziądz (powiat)", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.4500, lng: 18.7500, wiki: "Powiat_grudziądzki" },
      { kod: "CIN", nazwa: "Inowrocław", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.7989, lng: 18.2625, wiki: "Inowrocław" },
      { kod: "CLI", nazwa: "Lipno", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.8500, lng: 19.1750, wiki: "Lipno_(województwo_kujawsko-pomorskie)" },
      { kod: "CMG", nazwa: "Mogilno", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.6589, lng: 17.9583, wiki: "Mogilno" },
      { kod: "CNA", nazwa: "Nakło nad Notecią", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.1417, lng: 17.5969, wiki: "Nakło_nad_Notecią" },
      { kod: "CRA", nazwa: "Radziejów", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.6256, lng: 18.5314, wiki: "Radziejów" },
      { kod: "CRY", nazwa: "Rypin", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.0631, lng: 19.4106, wiki: "Rypin" },
      { kod: "CSE", nazwa: "Sępólno Krajeńskie", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.4561, lng: 17.5328, wiki: "Sępólno_Krajeńskie" },
      { kod: "CSW", nazwa: "Świecie", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.4097, lng: 18.4419, wiki: "Świecie" },
      { kod: "CTR", nazwa: "Toruń (powiat)", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.0500, lng: 18.6000, wiki: "Powiat_toruński" },
      { kod: "CTU", nazwa: "Tuchola", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.5867, lng: 17.8606, wiki: "Tuchola" },
      { kod: "CWA", nazwa: "Wąbrzeźno", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 53.2786, lng: 18.9522, wiki: "Wąbrzeźno" },
      { kod: "CWL", nazwa: "Włocławek (powiat)", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.6500, lng: 19.0500, wiki: "Powiat_włocławski" },
      { kod: "CZN", nazwa: "Żnin", typ: "ziemski", woj: "kujawsko-pomorskie", lat: 52.8497, lng: 17.7172, wiki: "Żnin" },

      // ========== LUBELSKIE (L) ==========
      { kod: "LB", nazwa: "Biała Podlaska", typ: "miasto", woj: "lubelskie", lat: 52.0325, lng: 23.1149, wiki: "Biała_Podlaska" },
      { kod: "LC", nazwa: "Chełm", typ: "miasto", woj: "lubelskie", lat: 51.1432, lng: 23.4716, wiki: "Chełm" },
      { kod: "LU", nazwa: "Lublin", typ: "miasto", woj: "lubelskie", lat: 51.2465, lng: 22.5684, wiki: "Lublin" },
      { kod: "LZ", nazwa: "Zamość", typ: "miasto", woj: "lubelskie", lat: 50.7231, lng: 23.2519, wiki: "Zamość" },
      { kod: "LBL", nazwa: "Biłgoraj", typ: "ziemski", woj: "lubelskie", lat: 50.5413, lng: 22.7227, wiki: "Biłgoraj" },
      { kod: "LBI", nazwa: "Biała Podlaska (powiat)", typ: "ziemski", woj: "lubelskie", lat: 52.0500, lng: 23.0500, wiki: "Powiat_bialski" },
      { kod: "LCH", nazwa: "Chełm (powiat)", typ: "ziemski", woj: "lubelskie", lat: 51.1500, lng: 23.5000, wiki: "Powiat_chełmski" },
      { kod: "LHR", nazwa: "Hrubieszów", typ: "ziemski", woj: "lubelskie", lat: 50.8050, lng: 23.8861, wiki: "Hrubieszów" },
      { kod: "LJA", nazwa: "Janów Lubelski", typ: "ziemski", woj: "lubelskie", lat: 50.7081, lng: 22.4131, wiki: "Janów_Lubelski" },
      { kod: "LKR", nazwa: "Krasnystaw", typ: "ziemski", woj: "lubelskie", lat: 50.9858, lng: 23.1719, wiki: "Krasnystaw" },
      { kod: "LKS", nazwa: "Kraśnik", typ: "ziemski", woj: "lubelskie", lat: 50.9242, lng: 22.2256, wiki: "Kraśnik" },
      { kod: "LLB", nazwa: "Lublin (powiat)", typ: "ziemski", woj: "lubelskie", lat: 51.2500, lng: 22.5500, wiki: "Powiat_lubelski" },
      { kod: "LLW", nazwa: "Lubartów", typ: "ziemski", woj: "lubelskie", lat: 51.4625, lng: 22.6072, wiki: "Lubartów" },
      { kod: "LLE", nazwa: "Łęczna", typ: "ziemski", woj: "lubelskie", lat: 51.3000, lng: 22.8833, wiki: "Łęczna" },
      { kod: "LLU", nazwa: "Łuków", typ: "ziemski", woj: "lubelskie", lat: 51.9281, lng: 22.3789, wiki: "Łuków" },
      { kod: "LOP", nazwa: "Opole Lubelskie", typ: "ziemski", woj: "lubelskie", lat: 51.1467, lng: 21.9683, wiki: "Opole_Lubelskie" },
      { kod: "LPA", nazwa: "Parczew", typ: "ziemski", woj: "lubelskie", lat: 51.6406, lng: 22.9000, wiki: "Parczew" },
      { kod: "LPU", nazwa: "Puławy", typ: "ziemski", woj: "lubelskie", lat: 51.4144, lng: 21.9694, wiki: "Puławy" },
      { kod: "LRA", nazwa: "Radzyń Podlaski", typ: "ziemski", woj: "lubelskie", lat: 51.7822, lng: 22.6217, wiki: "Radzyń_Podlaski" },
      { kod: "LRY", nazwa: "Ryki", typ: "ziemski", woj: "lubelskie", lat: 51.6256, lng: 21.9356, wiki: "Ryki" },
      { kod: "LSW", nazwa: "Świdnik", typ: "ziemski", woj: "lubelskie", lat: 51.2197, lng: 22.6964, wiki: "Świdnik" },
      { kod: "LTM", nazwa: "Tomaszów Lubelski", typ: "ziemski", woj: "lubelskie", lat: 50.4475, lng: 23.4194, wiki: "Tomaszów_Lubelski" },
      { kod: "LWL", nazwa: "Włodawa", typ: "ziemski", woj: "lubelskie", lat: 51.5489, lng: 23.5475, wiki: "Włodawa" },
      { kod: "LZA", nazwa: "Zamość (powiat)", typ: "ziemski", woj: "lubelskie", lat: 50.7000, lng: 23.2500, wiki: "Powiat_zamojski" },

      // ========== LUBUSKIE (F) ==========
      { kod: "FG", nazwa: "Gorzów Wielkopolski", typ: "miasto", woj: "lubuskie", lat: 52.7368, lng: 15.2288, wiki: "Gorzów_Wielkopolski" },
      { kod: "FZ", nazwa: "Zielona Góra", typ: "miasto", woj: "lubuskie", lat: 51.9356, lng: 15.5064, wiki: "Zielona_Góra" },
      { kod: "FGW", nazwa: "Gorzów (powiat)", typ: "ziemski", woj: "lubuskie", lat: 52.7500, lng: 15.2500, wiki: "Powiat_gorzowski" },
      { kod: "FKR", nazwa: "Krosno Odrzańskie", typ: "ziemski", woj: "lubuskie", lat: 52.0489, lng: 15.0975, wiki: "Krosno_Odrzańskie" },
      { kod: "FMI", nazwa: "Międzyrzecz", typ: "ziemski", woj: "lubuskie", lat: 52.4444, lng: 15.5781, wiki: "Międzyrzecz" },
      { kod: "FNW", nazwa: "Nowa Sól", typ: "ziemski", woj: "lubuskie", lat: 51.7969, lng: 15.7100, wiki: "Nowa_Sól" },
      { kod: "FSD", nazwa: "Strzelce Krajeńskie", typ: "ziemski", woj: "lubuskie", lat: 52.8758, lng: 15.5375, wiki: "Strzelce_Krajeńskie" },
      { kod: "FSL", nazwa: "Słubice", typ: "ziemski", woj: "lubuskie", lat: 52.3492, lng: 14.5594, wiki: "Słubice" },
      { kod: "FSU", nazwa: "Sulęcin", typ: "ziemski", woj: "lubuskie", lat: 52.4422, lng: 15.1156, wiki: "Sulęcin" },
      { kod: "FSW", nazwa: "Świebodzin", typ: "ziemski", woj: "lubuskie", lat: 52.2492, lng: 15.5333, wiki: "Świebodzin" },
      { kod: "FWS", nazwa: "Wschowa", typ: "ziemski", woj: "lubuskie", lat: 51.8019, lng: 16.3186, wiki: "Wschowa" },
      { kod: "FZG", nazwa: "Żagań", typ: "ziemski", woj: "lubuskie", lat: 51.6175, lng: 15.3147, wiki: "Żagań" },
      { kod: "FZI", nazwa: "Zielona Góra (powiat)", typ: "ziemski", woj: "lubuskie", lat: 51.9000, lng: 15.5000, wiki: "Powiat_zielonogórski" },
      { kod: "FZA", nazwa: "Żary", typ: "ziemski", woj: "lubuskie", lat: 51.6411, lng: 15.1322, wiki: "Żary" },

      // ========== ŁÓDZKIE (E) ==========
      { kod: "EL", nazwa: "Łódź", typ: "miasto", woj: "łódzkie", lat: 51.7592, lng: 19.4560, wiki: "Łódź" },
      { kod: "EP", nazwa: "Piotrków Trybunalski", typ: "miasto", woj: "łódzkie", lat: 51.4055, lng: 19.7030, wiki: "Piotrków_Trybunalski" },
      { kod: "ES", nazwa: "Skierniewice", typ: "miasto", woj: "łódzkie", lat: 51.9544, lng: 20.1572, wiki: "Skierniewice" },
      { kod: "EBE", nazwa: "Bełchatów", typ: "ziemski", woj: "łódzkie", lat: 51.3686, lng: 19.3553, wiki: "Bełchatów" },
      { kod: "EBR", nazwa: "Brzeziny", typ: "ziemski", woj: "łódzkie", lat: 51.8081, lng: 19.7497, wiki: "Brzeziny" },
      { kod: "EKU", nazwa: "Kutno", typ: "ziemski", woj: "łódzkie", lat: 52.2306, lng: 19.3653, wiki: "Kutno" },
      { kod: "ELA", nazwa: "Łask", typ: "ziemski", woj: "łódzkie", lat: 51.5908, lng: 19.1342, wiki: "Łask" },
      { kod: "ELE", nazwa: "Łęczyca", typ: "ziemski", woj: "łódzkie", lat: 52.0586, lng: 19.1969, wiki: "Łęczyca" },
      { kod: "ELW", nazwa: "Łódź Wschód", typ: "ziemski", woj: "łódzkie", lat: 51.7500, lng: 19.6000, wiki: "Powiat_łódzki_wschodni" },
      { kod: "ELC", nazwa: "Łowicz", typ: "ziemski", woj: "łódzkie", lat: 52.1075, lng: 19.9444, wiki: "Łowicz" },
      { kod: "EOP", nazwa: "Opoczno", typ: "ziemski", woj: "łódzkie", lat: 51.3786, lng: 20.2828, wiki: "Opoczno" },
      { kod: "EPA", nazwa: "Pabianice", typ: "ziemski", woj: "łódzkie", lat: 51.6644, lng: 19.3550, wiki: "Pabianice" },
      { kod: "EPI", nazwa: "Piotrków (powiat)", typ: "ziemski", woj: "łódzkie", lat: 51.4000, lng: 19.7000, wiki: "Powiat_piotrkowski" },
      { kod: "EPJ", nazwa: "Pajęczno", typ: "ziemski", woj: "łódzkie", lat: 51.1483, lng: 18.9886, wiki: "Pajęczno" },
      { kod: "EPD", nazwa: "Poddębice", typ: "ziemski", woj: "łódzkie", lat: 51.8917, lng: 18.9583, wiki: "Poddębice" },
      { kod: "ERA", nazwa: "Radomsko", typ: "ziemski", woj: "łódzkie", lat: 51.0683, lng: 19.4453, wiki: "Radomsko" },
      { kod: "ERW", nazwa: "Rawa Mazowiecka", typ: "ziemski", woj: "łódzkie", lat: 51.7656, lng: 20.2553, wiki: "Rawa_Mazowiecka" },
      { kod: "ESI", nazwa: "Sieradz", typ: "ziemski", woj: "łódzkie", lat: 51.5953, lng: 18.7308, wiki: "Sieradz" },
      { kod: "ESK", nazwa: "Skierniewice (powiat)", typ: "ziemski", woj: "łódzkie", lat: 51.9500, lng: 20.1500, wiki: "Powiat_skierniewicki" },
      { kod: "ETM", nazwa: "Tomaszów Mazowiecki", typ: "ziemski", woj: "łódzkie", lat: 51.5325, lng: 20.0089, wiki: "Tomaszów_Mazowiecki" },
      { kod: "EWE", nazwa: "Wieluń", typ: "ziemski", woj: "łódzkie", lat: 51.2208, lng: 18.5694, wiki: "Wieluń" },
      { kod: "EWI", nazwa: "Wieruszów", typ: "ziemski", woj: "łódzkie", lat: 51.2917, lng: 18.1572, wiki: "Wieruszów" },
      { kod: "EZD", nazwa: "Zduńska Wola", typ: "ziemski", woj: "łódzkie", lat: 51.6000, lng: 18.9333, wiki: "Zduńska_Wola" },
      { kod: "EZG", nazwa: "Zgierz", typ: "ziemski", woj: "łódzkie", lat: 51.8556, lng: 19.4053, wiki: "Zgierz" },

      // ========== MAŁOPOLSKIE (K) ==========
      { kod: "KR", nazwa: "Kraków", typ: "miasto", woj: "małopolskie", lat: 50.0647, lng: 19.9450, wiki: "Kraków" },
      { kod: "KN", nazwa: "Nowy Sącz", typ: "miasto", woj: "małopolskie", lat: 49.6175, lng: 20.7156, wiki: "Nowy_Sącz" },
      { kod: "KT", nazwa: "Tarnów", typ: "miasto", woj: "małopolskie", lat: 50.0140, lng: 20.9839, wiki: "Tarnów" },
      { kod: "KBC", nazwa: "Bochnia", typ: "ziemski", woj: "małopolskie", lat: 49.9697, lng: 20.4308, wiki: "Bochnia" },
      { kod: "KBR", nazwa: "Brzesko", typ: "ziemski", woj: "małopolskie", lat: 49.9706, lng: 20.6056, wiki: "Brzesko" },
      { kod: "KCH", nazwa: "Chrzanów", typ: "ziemski", woj: "małopolskie", lat: 50.1361, lng: 19.4036, wiki: "Chrzanów" },
      { kod: "KDA", nazwa: "Dąbrowa Tarnowska", typ: "ziemski", woj: "małopolskie", lat: 50.1747, lng: 20.9886, wiki: "Dąbrowa_Tarnowska" },
      { kod: "KGR", nazwa: "Gorlice", typ: "ziemski", woj: "małopolskie", lat: 49.6553, lng: 21.1611, wiki: "Gorlice" },
      { kod: "KKR", nazwa: "Kraków (powiat)", typ: "ziemski", woj: "małopolskie", lat: 50.0500, lng: 20.0000, wiki: "Powiat_krakowski" },
      { kod: "KLI", nazwa: "Limanowa", typ: "ziemski", woj: "małopolskie", lat: 49.7050, lng: 20.4253, wiki: "Limanowa" },
      { kod: "KMI", nazwa: "Miechów", typ: "ziemski", woj: "małopolskie", lat: 50.3578, lng: 20.0297, wiki: "Miechów" },
      { kod: "KMY", nazwa: "Myślenice", typ: "ziemski", woj: "małopolskie", lat: 49.8344, lng: 19.9389, wiki: "Myślenice" },
      { kod: "KNS", nazwa: "Nowy Sącz (powiat)", typ: "ziemski", woj: "małopolskie", lat: 49.6000, lng: 20.7500, wiki: "Powiat_nowosądecki" },
      { kod: "KNT", nazwa: "Nowy Targ", typ: "ziemski", woj: "małopolskie", lat: 49.4778, lng: 20.0306, wiki: "Nowy_Targ" },
      { kod: "KOL", nazwa: "Olkusz", typ: "ziemski", woj: "małopolskie", lat: 50.2789, lng: 19.5644, wiki: "Olkusz" },
      { kod: "KOS", nazwa: "Oświęcim", typ: "ziemski", woj: "małopolskie", lat: 50.0344, lng: 19.2098, wiki: "Oświęcim" },
      { kod: "KPR", nazwa: "Proszowice", typ: "ziemski", woj: "małopolskie", lat: 50.1942, lng: 20.2864, wiki: "Proszowice" },
      { kod: "KSU", nazwa: "Sucha Beskidzka", typ: "ziemski", woj: "małopolskie", lat: 49.7414, lng: 19.5919, wiki: "Sucha_Beskidzka" },
      { kod: "KTA", nazwa: "Tarnów (powiat)", typ: "ziemski", woj: "małopolskie", lat: 50.0000, lng: 21.0000, wiki: "Powiat_tarnowski" },
      { kod: "KTT", nazwa: "Tatrzański (Zakopane)", typ: "ziemski", woj: "małopolskie", lat: 49.2992, lng: 19.9494, wiki: "Powiat_tatrzański" },
      { kod: "KWA", nazwa: "Wadowice", typ: "ziemski", woj: "małopolskie", lat: 49.8839, lng: 19.4906, wiki: "Wadowice" },
      { kod: "KWI", nazwa: "Wieliczka", typ: "ziemski", woj: "małopolskie", lat: 49.9869, lng: 20.0644, wiki: "Wieliczka" },

      // ========== MAZOWIECKIE (W) ==========
      { kod: "WA", nazwa: "Warszawa - Białołęka", typ: "miasto", woj: "mazowieckie", lat: 52.3211, lng: 20.9700, wiki: "Białołęka" },
      { kod: "WB", nazwa: "Warszawa - Bemowo", typ: "miasto", woj: "mazowieckie", lat: 52.2500, lng: 20.9100, wiki: "Bemowo" },
      { kod: "WD", nazwa: "Warszawa - Bielany", typ: "miasto", woj: "mazowieckie", lat: 52.2900, lng: 20.9400, wiki: "Bielany_(Warszawa)" },
      { kod: "WE", nazwa: "Warszawa - Mokotów", typ: "miasto", woj: "mazowieckie", lat: 52.1900, lng: 21.0400, wiki: "Mokotów" },
      { kod: "WF", nazwa: "Warszawa - Praga Płd.", typ: "miasto", woj: "mazowieckie", lat: 52.2400, lng: 21.0900, wiki: "Praga-Południe" },
      { kod: "WH", nazwa: "Warszawa - Praga Płn.", typ: "miasto", woj: "mazowieckie", lat: 52.2600, lng: 21.0500, wiki: "Praga-Północ" },
      { kod: "WI", nazwa: "Warszawa - Śródmieście", typ: "miasto", woj: "mazowieckie", lat: 52.2297, lng: 21.0122, wiki: "Śródmieście_(Warszawa)" },
      { kod: "WJ", nazwa: "Warszawa - Targówek", typ: "miasto", woj: "mazowieckie", lat: 52.2900, lng: 21.0700, wiki: "Targówek" },
      { kod: "WK", nazwa: "Warszawa - Ursus", typ: "miasto", woj: "mazowieckie", lat: 52.1950, lng: 20.8850, wiki: "Ursus_(Warszawa)" },
      { kod: "WN", nazwa: "Warszawa - Ursynów", typ: "miasto", woj: "mazowieckie", lat: 52.1500, lng: 21.0500, wiki: "Ursynów" },
      { kod: "WT", nazwa: "Warszawa - Wawer", typ: "miasto", woj: "mazowieckie", lat: 52.2000, lng: 21.1500, wiki: "Wawer" },
      { kod: "WU", nazwa: "Warszawa - Ochota", typ: "miasto", woj: "mazowieckie", lat: 52.2050, lng: 20.9700, wiki: "Ochota" },
      { kod: "WW", nazwa: "Warszawa - Wilanów", typ: "miasto", woj: "mazowieckie", lat: 52.1650, lng: 21.0900, wiki: "Wilanów" },
      { kod: "WW", nazwa: "Warszawa - Włochy", typ: "miasto", woj: "mazowieckie", lat: 52.1900, lng: 20.9400, wiki: "Włochy_(Warszawa)" },
      { kod: "WX", nazwa: "Warszawa - Żoliborz", typ: "miasto", woj: "mazowieckie", lat: 52.2683, lng: 20.9814, wiki: "Żoliborz" },
      { kod: "WY", nazwa: "Warszawa - Wola", typ: "miasto", woj: "mazowieckie", lat: 52.2370, lng: 20.9700, wiki: "Wola_(Warszawa)" },
      
      { kod: "WO", nazwa: "Ostrołęka", typ: "miasto", woj: "mazowieckie", lat: 53.0865, lng: 21.5742, wiki: "Ostrołęka" },
      { kod: "WP", nazwa: "Płock", typ: "miasto", woj: "mazowieckie", lat: 52.5463, lng: 19.7065, wiki: "Płock" },
      { kod: "WR", nazwa: "Radom", typ: "miasto", woj: "mazowieckie", lat: 51.4027, lng: 21.1471, wiki: "Radom" },
      { kod: "WS", nazwa: "Siedlce", typ: "miasto", woj: "mazowieckie", lat: 52.1676, lng: 22.2902, wiki: "Siedlce" },
      { kod: "WBI", nazwa: "Białobrzegi", typ: "ziemski", woj: "mazowieckie", lat: 51.6442, lng: 20.9569, wiki: "Białobrzegi" },
      { kod: "WCI", nazwa: "Ciechanów", typ: "ziemski", woj: "mazowieckie", lat: 52.8814, lng: 20.6175, wiki: "Ciechanów" },
      { kod: "WG", nazwa: "Garwolin", typ: "ziemski", woj: "mazowieckie", lat: 51.8967, lng: 21.6122, wiki: "Garwolin" },
      { kod: "WGS", nazwa: "Gostynin", typ: "ziemski", woj: "mazowieckie", lat: 52.4314, lng: 19.4658, wiki: "Gostynin" },
      { kod: "WGM", nazwa: "Grodzisk Mazowiecki", typ: "ziemski", woj: "mazowieckie", lat: 52.1083, lng: 20.6250, wiki: "Grodzisk_Mazowiecki" },
      { kod: "WGR", nazwa: "Grójec", typ: "ziemski", woj: "mazowieckie", lat: 51.8628, lng: 20.8678, wiki: "Grójec" },
      { kod: "WKZ", nazwa: "Kozienice", typ: "ziemski", woj: "mazowieckie", lat: 51.5808, lng: 21.5500, wiki: "Kozienice" },
      { kod: "WL", nazwa: "Legionowo", typ: "ziemski", woj: "mazowieckie", lat: 52.4044, lng: 20.9233, wiki: "Legionowo" },
      { kod: "WLI", nazwa: "Lipsko", typ: "ziemski", woj: "mazowieckie", lat: 51.1592, lng: 21.6500, wiki: "Lipsko" },
      { kod: "WLS", nazwa: "Łosice", typ: "ziemski", woj: "mazowieckie", lat: 52.2117, lng: 22.7222, wiki: "Łosice" },
      { kod: "WM", nazwa: "Mińsk Mazowiecki", typ: "ziemski", woj: "mazowieckie", lat: 52.1817, lng: 21.5617, wiki: "Mińsk_Mazowiecki" },
      { kod: "WMA", nazwa: "Maków Mazowiecki", typ: "ziemski", woj: "mazowieckie", lat: 52.8589, lng: 21.0997, wiki: "Maków_Mazowiecki" },
      { kod: "WML", nazwa: "Mława", typ: "ziemski", woj: "mazowieckie", lat: 53.1119, lng: 20.3819, wiki: "Mława" },
      { kod: "WND", nazwa: "Nowy Dwór Mazowiecki", typ: "ziemski", woj: "mazowieckie", lat: 52.4408, lng: 20.7158, wiki: "Nowy_Dwór_Mazowiecki" },
      { kod: "WOS", nazwa: "Ostrołęka (powiat)", typ: "ziemski", woj: "mazowieckie", lat: 53.0500, lng: 21.5500, wiki: "Powiat_ostrołęcki" },
      { kod: "WOR", nazwa: "Ostrów Mazowiecka", typ: "ziemski", woj: "mazowieckie", lat: 52.8033, lng: 21.8900, wiki: "Ostrów_Mazowiecka" },
      { kod: "WOT", nazwa: "Otwock", typ: "ziemski", woj: "mazowieckie", lat: 52.1056, lng: 21.2614, wiki: "Otwock" },
      { kod: "WPI", nazwa: "Piaseczno", typ: "ziemski", woj: "mazowieckie", lat: 52.0808, lng: 21.0233, wiki: "Piaseczno" },
      { kod: "WPL", nazwa: "Płock (powiat)", typ: "ziemski", woj: "mazowieckie", lat: 52.5500, lng: 19.7000, wiki: "Powiat_płocki" },
      { kod: "WPN", nazwa: "Płońsk", typ: "ziemski", woj: "mazowieckie", lat: 52.6258, lng: 20.3789, wiki: "Płońsk" },
      { kod: "WPR", nazwa: "Pruszków", typ: "ziemski", woj: "mazowieckie", lat: 52.1700, lng: 20.8000, wiki: "Pruszków" },
      { kod: "WPZ", nazwa: "Przasnysz", typ: "ziemski", woj: "mazowieckie", lat: 53.0214, lng: 20.8786, wiki: "Przasnysz" },
      { kod: "WPY", nazwa: "Przysucha", typ: "ziemski", woj: "mazowieckie", lat: 51.3578, lng: 20.6311, wiki: "Przysucha" },
      { kod: "WPU", nazwa: "Pułtusk", typ: "ziemski", woj: "mazowieckie", lat: 52.7058, lng: 21.0867, wiki: "Pułtusk" },
      { kod: "WRA", nazwa: "Radom (powiat)", typ: "ziemski", woj: "mazowieckie", lat: 51.4000, lng: 21.1500, wiki: "Powiat_radomski" },
      { kod: "WSC", nazwa: "Sochaczew", typ: "ziemski", woj: "mazowieckie", lat: 52.2289, lng: 20.2400, wiki: "Sochaczew" },
      { kod: "WSE", nazwa: "Siedlce (powiat)", typ: "ziemski", woj: "mazowieckie", lat: 52.1500, lng: 22.3000, wiki: "Powiat_siedlecki" },
      { kod: "WSI", nazwa: "Sierpc", typ: "ziemski", woj: "mazowieckie", lat: 52.8589, lng: 19.6692, wiki: "Sierpc" },
      { kod: "WSK", nazwa: "Sokołów Podlaski", typ: "ziemski", woj: "mazowieckie", lat: 52.4106, lng: 22.2469, wiki: "Sokołów_Podlaski" },
      { kod: "WSZ", nazwa: "Szydłowiec", typ: "ziemski", woj: "mazowieckie", lat: 51.2356, lng: 20.8508, wiki: "Szydłowiec" },
      { kod: "WWE", nazwa: "Węgrów", typ: "ziemski", woj: "mazowieckie", lat: 52.4067, lng: 22.0094, wiki: "Węgrów" },
      { kod: "WWL", nazwa: "Wołomin", typ: "ziemski", woj: "mazowieckie", lat: 52.3414, lng: 21.2406, wiki: "Wołomin" },
      { kod: "WWY", nazwa: "Wyszków", typ: "ziemski", woj: "mazowieckie", lat: 52.5917, lng: 21.4631, wiki: "Wyszków" },
      { kod: "WZ", nazwa: "Warszawa Zachodnia (Ożarów)", typ: "ziemski", woj: "mazowieckie", lat: 52.2089, lng: 20.7239, wiki: "Powiat_warszawski_zachodni" },
      { kod: "WZW", nazwa: "Zwoleń", typ: "ziemski", woj: "mazowieckie", lat: 51.3611, lng: 21.5844, wiki: "Zwoleń" },
      { kod: "WZU", nazwa: "Żuromin", typ: "ziemski", woj: "mazowieckie", lat: 53.0653, lng: 19.9100, wiki: "Żuromin" },
      { kod: "WZY", nazwa: "Żyrardów", typ: "ziemski", woj: "mazowieckie", lat: 52.0489, lng: 20.4456, wiki: "Żyrardów" },

      // ========== OPOLSKIE (O) ==========
      { kod: "OP", nazwa: "Opole", typ: "miasto", woj: "opolskie", lat: 50.6751, lng: 17.9213, wiki: "Opole" },
      { kod: "OB", nazwa: "Brzeg", typ: "ziemski", woj: "opolskie", lat: 50.8606, lng: 17.4683, wiki: "Brzeg" },
      { kod: "OGL", nazwa: "Głubczyce", typ: "ziemski", woj: "opolskie", lat: 50.2017, lng: 17.8264, wiki: "Głubczyce" },
      { kod: "OK", nazwa: "Kędzierzyn-Koźle", typ: "ziemski", woj: "opolskie", lat: 50.3494, lng: 18.2261, wiki: "Kędzierzyn-Koźle" },
      { kod: "OKL", nazwa: "Kluczbork", typ: "ziemski", woj: "opolskie", lat: 50.9714, lng: 18.2208, wiki: "Kluczbork" },
      { kod: "OKR", nazwa: "Krapkowice", typ: "ziemski", woj: "opolskie", lat: 50.4761, lng: 17.9656, wiki: "Krapkowice" },
      { kod: "ONA", nazwa: "Namysłów", typ: "ziemski", woj: "opolskie", lat: 51.0786, lng: 17.7233, wiki: "Namysłów" },
      { kod: "ONY", nazwa: "Nysa", typ: "ziemski", woj: "opolskie", lat: 50.4742, lng: 17.3328, wiki: "Nysa" },
      { kod: "OOL", nazwa: "Olesno", typ: "ziemski", woj: "opolskie", lat: 50.8722, lng: 18.4181, wiki: "Olesno" },
      { kod: "OPO", nazwa: "Opole (powiat)", typ: "ziemski", woj: "opolskie", lat: 50.6500, lng: 17.9000, wiki: "Powiat_opolski_(województwo_opolskie)" },
      { kod: "OPR", nazwa: "Prudnik", typ: "ziemski", woj: "opolskie", lat: 50.3236, lng: 17.5786, wiki: "Prudnik" },
      { kod: "OST", nazwa: "Strzelce Opolskie", typ: "ziemski", woj: "opolskie", lat: 50.5125, lng: 18.3050, wiki: "Strzelce_Opolskie" },

      // ========== PODKARPACKIE (R) ==========
      { kod: "RZ", nazwa: "Rzeszów", typ: "miasto", woj: "podkarpackie", lat: 50.0413, lng: 21.9990, wiki: "Rzeszów" },
      { kod: "RK", nazwa: "Krosno", typ: "miasto", woj: "podkarpackie", lat: 49.6883, lng: 21.7706, wiki: "Krosno" },
      { kod: "RP", nazwa: "Przemyśl", typ: "miasto", woj: "podkarpackie", lat: 49.7836, lng: 22.7676, wiki: "Przemyśl" },
      { kod: "RT", nazwa: "Tarnobrzeg", typ: "miasto", woj: "podkarpackie", lat: 50.5731, lng: 21.6797, wiki: "Tarnobrzeg" },
      { kod: "RBI", nazwa: "Bieszczady (Ustrzyki Dolne)", typ: "ziemski", woj: "podkarpackie", lat: 49.4297, lng: 22.5933, wiki: "Powiat_bieszczadzki" },
      { kod: "RBR", nazwa: "Brzozów", typ: "ziemski", woj: "podkarpackie", lat: 49.6936, lng: 22.0186, wiki: "Brzozów" },
      { kod: "RDE", nazwa: "Dębica", typ: "ziemski", woj: "podkarpackie", lat: 50.0511, lng: 21.4117, wiki: "Dębica" },
      { kod: "RJA", nazwa: "Jarosław", typ: "ziemski", woj: "podkarpackie", lat: 50.0167, lng: 22.6789, wiki: "Jarosław_(województwo_podkarpackie)" },
      { kod: "RJS", nazwa: "Jasło", typ: "ziemski", woj: "podkarpackie", lat: 49.7456, lng: 21.4717, wiki: "Jasło" },
      { kod: "RKL", nazwa: "Kolbuszowa", typ: "ziemski", woj: "podkarpackie", lat: 50.2469, lng: 21.7783, wiki: "Kolbuszowa" },
      { kod: "RKR", nazwa: "Krosno (powiat)", typ: "ziemski", woj: "podkarpackie", lat: 49.6500, lng: 21.7500, wiki: "Powiat_krośnieński_(województwo_podkarpackie)" },
      { kod: "RLS", nazwa: "Lesko", typ: "ziemski", woj: "podkarpackie", lat: 49.4694, lng: 22.3306, wiki: "Lesko" },
      { kod: "RLE", nazwa: "Leżajsk", typ: "ziemski", woj: "podkarpackie", lat: 50.2647, lng: 22.4194, wiki: "Leżajsk" },
      { kod: "RLU", nazwa: "Lubaczów", typ: "ziemski", woj: "podkarpackie", lat: 50.1567, lng: 23.1186, wiki: "Lubaczów" },
      { kod: "RLA", nazwa: "Łańcut", typ: "ziemski", woj: "podkarpackie", lat: 50.0683, lng: 22.2300, wiki: "Łańcut" },
      { kod: "RMI", nazwa: "Mielec", typ: "ziemski", woj: "podkarpackie", lat: 50.2872, lng: 21.4239, wiki: "Mielec" },
      { kod: "RNI", nazwa: "Nisko", typ: "ziemski", woj: "podkarpackie", lat: 50.5217, lng: 22.1431, wiki: "Nisko" },
      { kod: "RPR", nazwa: "Przemyśl (powiat)", typ: "ziemski", woj: "podkarpackie", lat: 49.7800, lng: 22.7500, wiki: "Powiat_przemyski" },
      { kod: "RPZ", nazwa: "Przeworsk", typ: "ziemski", woj: "podkarpackie", lat: 50.0589, lng: 22.4944, wiki: "Przeworsk" },
      { kod: "RRS", nazwa: "Ropczyce-Sędziszów", typ: "ziemski", woj: "podkarpackie", lat: 50.0539, lng: 21.6072, wiki: "Powiat_ropczycko-sędziszowski" },
      { kod: "RRZ", nazwa: "Rzeszów (powiat)", typ: "ziemski", woj: "podkarpackie", lat: 50.0500, lng: 22.0000, wiki: "Powiat_rzeszowski" },
      { kod: "RSA", nazwa: "Sanok", typ: "ziemski", woj: "podkarpackie", lat: 49.5556, lng: 22.2058, wiki: "Sanok" },
      { kod: "RST", nazwa: "Stalowa Wola", typ: "ziemski", woj: "podkarpackie", lat: 50.5811, lng: 22.0539, wiki: "Stalowa_Wola" },
      { kod: "RSR", nazwa: "Strzyżów", typ: "ziemski", woj: "podkarpackie", lat: 49.8722, lng: 21.7944, wiki: "Strzyżów" },
      { kod: "RTA", nazwa: "Tarnobrzeg (powiat)", typ: "ziemski", woj: "podkarpackie", lat: 50.5500, lng: 21.7000, wiki: "Powiat_tarnobrzeski" },

      // ========== PODLASKIE (B) ==========
      { kod: "BI", nazwa: "Białystok", typ: "miasto", woj: "podlaskie", lat: 53.1325, lng: 23.1688, wiki: "Białystok" },
      { kod: "BL", nazwa: "Łomża", typ: "miasto", woj: "podlaskie", lat: 53.1781, lng: 22.0589, wiki: "Łomża" },
      { kod: "BS", nazwa: "Suwałki", typ: "miasto", woj: "podlaskie", lat: 54.1117, lng: 22.9306, wiki: "Suwałki" },
      { kod: "BAU", nazwa: "Augustów", typ: "ziemski", woj: "podlaskie", lat: 53.8439, lng: 22.9794, wiki: "Augustów" },
      { kod: "BIA", nazwa: "Białystok (powiat)", typ: "ziemski", woj: "podlaskie", lat: 53.1500, lng: 23.1500, wiki: "Powiat_białostocki" },
      { kod: "BBI", nazwa: "Bielsk Podlaski", typ: "ziemski", woj: "podlaskie", lat: 52.7672, lng: 23.1872, wiki: "Bielsk_Podlaski" },
      { kod: "BGR", nazwa: "Grajewo", typ: "ziemski", woj: "podlaskie", lat: 53.6483, lng: 22.4567, wiki: "Grajewo" },
      { kod: "BHA", nazwa: "Hajnówka", typ: "ziemski", woj: "podlaskie", lat: 52.7378, lng: 23.5750, wiki: "Hajnówka" },
      { kod: "BKL", nazwa: "Kolno", typ: "ziemski", woj: "podlaskie", lat: 53.4128, lng: 21.9258, wiki: "Kolno_(województwo_podlaskie)" },
      { kod: "BLM", nazwa: "Łomża (powiat)", typ: "ziemski", woj: "podlaskie", lat: 53.1500, lng: 22.0500, wiki: "Powiat_łomżyński" },
      { kod: "BMN", nazwa: "Mońki", typ: "ziemski", woj: "podlaskie", lat: 53.4019, lng: 22.7989, wiki: "Mońki" },
      { kod: "BSE", nazwa: "Sejny", typ: "ziemski", woj: "podlaskie", lat: 54.1083, lng: 23.3500, wiki: "Sejny" },
      { kod: "BSI", nazwa: "Siemiatycze", typ: "ziemski", woj: "podlaskie", lat: 52.4267, lng: 22.8639, wiki: "Siemiatycze" },
      { kod: "BSK", nazwa: "Sokółka", typ: "ziemski", woj: "podlaskie", lat: 53.4083, lng: 23.5022, wiki: "Sokółka" },
      { kod: "BSU", nazwa: "Suwałki (powiat)", typ: "ziemski", woj: "podlaskie", lat: 54.1000, lng: 22.9500, wiki: "Powiat_suwalski" },
      { kod: "BWM", nazwa: "Wysokie Mazowieckie", typ: "ziemski", woj: "podlaskie", lat: 52.9189, lng: 22.5142, wiki: "Wysokie_Mazowieckie" },
      { kod: "BZA", nazwa: "Zambrów", typ: "ziemski", woj: "podlaskie", lat: 52.9858, lng: 22.2433, wiki: "Zambrów" },

      // ========== POMORSKIE (G) ==========
      { kod: "GD", nazwa: "Gdańsk", typ: "miasto", woj: "pomorskie", lat: 54.3520, lng: 18.6466, wiki: "Gdańsk" },
      { kod: "GA", nazwa: "Gdynia", typ: "miasto", woj: "pomorskie", lat: 54.5189, lng: 18.5305, wiki: "Gdynia" },
      { kod: "GSP", nazwa: "Sopot", typ: "miasto", woj: "pomorskie", lat: 54.4419, lng: 18.5601, wiki: "Sopot" },
      { kod: "GS", nazwa: "Słupsk", typ: "miasto", woj: "pomorskie", lat: 54.4641, lng: 17.0285, wiki: "Słupsk" },
      { kod: "GBY", nazwa: "Bytów", typ: "ziemski", woj: "pomorskie", lat: 54.1697, lng: 17.4894, wiki: "Bytów" },
      { kod: "GCH", nazwa: "Chojnice", typ: "ziemski", woj: "pomorskie", lat: 53.6953, lng: 17.5564, wiki: "Chojnice" },
      { kod: "GCZ", nazwa: "Człuchów", typ: "ziemski", woj: "pomorskie", lat: 53.6664, lng: 17.3597, wiki: "Człuchów" },
      { kod: "GDA", nazwa: "Gdańsk (powiat - Pruszcz Gd.)", typ: "ziemski", woj: "pomorskie", lat: 54.2614, lng: 18.6358, wiki: "Powiat_gdański" },
      { kod: "GKA", nazwa: "Kartuzy", typ: "ziemski", woj: "pomorskie", lat: 54.3344, lng: 18.1981, wiki: "Kartuzy" },
      { kod: "GKS", nazwa: "Kościerzyna", typ: "ziemski", woj: "pomorskie", lat: 54.1228, lng: 17.9789, wiki: "Kościerzyna" },
      { kod: "GKW", nazwa: "Kwidzyn", typ: "ziemski", woj: "pomorskie", lat: 53.7297, lng: 18.9303, wiki: "Kwidzyn" },
      { kod: "GLE", nazwa: "Lębork", typ: "ziemski", woj: "pomorskie", lat: 54.5417, lng: 17.7522, wiki: "Lębork" },
      { kod: "GMB", nazwa: "Malbork", typ: "ziemski", woj: "pomorskie", lat: 54.0356, lng: 19.0264, wiki: "Malbork" },
      { kod: "GNM", nazwa: "Nowy Dwór Gdański", typ: "ziemski", woj: "pomorskie", lat: 54.2117, lng: 19.1206, wiki: "Nowy_Dwór_Gdański" },
      { kod: "GPU", nazwa: "Puck", typ: "ziemski", woj: "pomorskie", lat: 54.7186, lng: 18.4097, wiki: "Puck" },
      { kod: "GSL", nazwa: "Słupsk (powiat)", typ: "ziemski", woj: "pomorskie", lat: 54.4500, lng: 17.0500, wiki: "Powiat_słupski" },
      { kod: "GST", nazwa: "Starogard Gdański", typ: "ziemski", woj: "pomorskie", lat: 53.9722, lng: 18.5300, wiki: "Starogard_Gdański" },
      { kod: "GSZ", nazwa: "Sztum", typ: "ziemski", woj: "pomorskie", lat: 53.9156, lng: 19.0306, wiki: "Sztum" },
      { kod: "GTC", nazwa: "Tczew", typ: "ziemski", woj: "pomorskie", lat: 54.0917, lng: 18.7783, wiki: "Tczew" },
      { kod: "GWE", nazwa: "Wejherowo", typ: "ziemski", woj: "pomorskie", lat: 54.6058, lng: 18.2364, wiki: "Wejherowo" },

      // ========== ŚLĄSKIE (S) ==========
      { kod: "SK", nazwa: "Katowice", typ: "miasto", woj: "śląskie", lat: 50.2649, lng: 19.0238, wiki: "Katowice" },
      { kod: "SY", nazwa: "Bytom", typ: "miasto", woj: "śląskie", lat: 50.3478, lng: 18.9275, wiki: "Bytom" },
      { kod: "SH", nazwa: "Chorzów", typ: "miasto", woj: "śląskie", lat: 50.2972, lng: 18.9544, wiki: "Chorzów" },
      { kod: "SC", nazwa: "Częstochowa", typ: "miasto", woj: "śląskie", lat: 50.8118, lng: 19.1203, wiki: "Częstochowa" },
      { kod: "SD", nazwa: "Dąbrowa Górnicza", typ: "miasto", woj: "śląskie", lat: 50.3247, lng: 19.1956, wiki: "Dąbrowa_Górnicza" },
      { kod: "SG", nazwa: "Gliwice", typ: "miasto", woj: "śląskie", lat: 50.2945, lng: 18.6714, wiki: "Gliwice" },
      { kod: "SJZ", nazwa: "Jastrzębie-Zdrój", typ: "miasto", woj: "śląskie", lat: 49.9498, lng: 18.5760, wiki: "Jastrzębie-Zdrój" },
      { kod: "SJ", nazwa: "Jaworzno", typ: "miasto", woj: "śląskie", lat: 50.2049, lng: 19.2747, wiki: "Jaworzno" },
      { kod: "SM", nazwa: "Mysłowice", typ: "miasto", woj: "śląskie", lat: 50.2415, lng: 19.1356, wiki: "Mysłowice" },
      { kod: "SO", nazwa: "Sosnowiec", typ: "miasto", woj: "śląskie", lat: 50.2860, lng: 19.1042, wiki: "Sosnowiec" },
      { kod: "SPI", nazwa: "Piekary Śląskie", typ: "miasto", woj: "śląskie", lat: 50.3892, lng: 18.9300, wiki: "Piekary_Śląskie" },
      { kod: "SRS", nazwa: "Ruda Śląska", typ: "miasto", woj: "śląskie", lat: 50.2585, lng: 18.8567, wiki: "Ruda_Śląska" },
      { kod: "SR", nazwa: "Rybnik", typ: "miasto", woj: "śląskie", lat: 50.0971, lng: 18.5410, wiki: "Rybnik" },
      { kod: "SI", nazwa: "Siemianowice Śląskie", typ: "miasto", woj: "śląskie", lat: 50.3108, lng: 19.0225, wiki: "Siemianowice_Śląskie" },
      { kod: "SW", nazwa: "Świętochłowice", typ: "miasto", woj: "śląskie", lat: 50.3017, lng: 18.9189, wiki: "Świętochłowice" },
      { kod: "ST", nazwa: "Tychy", typ: "miasto", woj: "śląskie", lat: 50.1357, lng: 18.9985, wiki: "Tychy" },
      { kod: "SZ", nazwa: "Zabrze", typ: "miasto", woj: "śląskie", lat: 50.3249, lng: 18.7857, wiki: "Zabrze" },
      { kod: "SZO", nazwa: "Żory", typ: "miasto", woj: "śląskie", lat: 50.0453, lng: 18.7008, wiki: "Żory" }, // Updated to SZO 
      { kod: "SB", nazwa: "Bielsko-Biała", typ: "miasto", woj: "śląskie", lat: 49.8224, lng: 19.0447, wiki: "Bielsko-Biała" },
      { kod: "SBE", nazwa: "Będzin", typ: "ziemski", woj: "śląskie", lat: 50.3267, lng: 19.1308, wiki: "Będzin" },
      { kod: "SBI", nazwa: "Bielsko (powiat)", typ: "ziemski", woj: "śląskie", lat: 49.8000, lng: 19.0500, wiki: "Powiat_bielski_(województwo_śląskie)" },
      { kod: "SBL", nazwa: "Bieruń-Lędziny", typ: "ziemski", woj: "śląskie", lat: 50.0939, lng: 19.0894, wiki: "Powiat_bieruńsko-lędziński" },
      { kod: "SCI", nazwa: "Cieszyn", typ: "ziemski", woj: "śląskie", lat: 49.7497, lng: 18.6306, wiki: "Cieszyn" },
      { kod: "SCZ", nazwa: "Częstochowa (powiat)", typ: "ziemski", woj: "śląskie", lat: 50.8000, lng: 19.1000, wiki: "Powiat_częstochowski" },
      { kod: "SGL", nazwa: "Gliwice (powiat)", typ: "ziemski", woj: "śląskie", lat: 50.3000, lng: 18.5000, wiki: "Powiat_gliwicki" },
      { kod: "SKL", nazwa: "Kłobuck", typ: "ziemski", woj: "śląskie", lat: 50.9097, lng: 18.9358, wiki: "Kłobuck" },
      { kod: "SLU", nazwa: "Lubliniec", typ: "ziemski", woj: "śląskie", lat: 50.6692, lng: 18.6856, wiki: "Lubliniec" },
      { kod: "SMI", nazwa: "Mikołów", typ: "ziemski", woj: "śląskie", lat: 50.1722, lng: 18.9061, wiki: "Mikołów" },
      { kod: "SMY", nazwa: "Myszków", typ: "ziemski", woj: "śląskie", lat: 50.5644, lng: 19.3306, wiki: "Myszków" },
      { kod: "SPS", nazwa: "Pszczyna", typ: "ziemski", woj: "śląskie", lat: 49.9817, lng: 18.9442, wiki: "Pszczyna" },
      { kod: "SRC", nazwa: "Racibórz", typ: "ziemski", woj: "śląskie", lat: 50.0917, lng: 18.2192, wiki: "Racibórz" }, // Fixed Racibórz from SRA to SRC
      { kod: "SRB", nazwa: "Rybnik (powiat)", typ: "ziemski", woj: "śląskie", lat: 50.1000, lng: 18.5000, wiki: "Powiat_rybnicki" }, // Fixed from SRC to SRB
      { kod: "STA", nazwa: "Tarnowskie Góry", typ: "ziemski", woj: "śląskie", lat: 50.4458, lng: 18.8606, wiki: "Tarnowskie_Góry" },
      { kod: "SWD", nazwa: "Wodzisław Śląski", typ: "ziemski", woj: "śląskie", lat: 50.0036, lng: 18.4636, wiki: "Wodzisław_Śląski" },
      { kod: "SZA", nazwa: "Zawiercie", typ: "ziemski", woj: "śląskie", lat: 50.4881, lng: 19.4156, wiki: "Zawiercie" },
      { kod: "SZY", nazwa: "Żywiec", typ: "ziemski", woj: "śląskie", lat: 49.6856, lng: 19.1925, wiki: "Żywiec" },

      // ========== ŚWIĘTOKRZYSKIE (T) ==========
      { kod: "TK", nazwa: "Kielce", typ: "miasto", woj: "świętokrzyskie", lat: 50.8661, lng: 20.6286, wiki: "Kielce" },
      { kod: "TBU", nazwa: "Busko-Zdrój", typ: "ziemski", woj: "świętokrzyskie", lat: 50.4711, lng: 20.7172, wiki: "Busko-Zdrój" },
      { kod: "TJE", nazwa: "Jędrzejów", typ: "ziemski", woj: "świętokrzyskie", lat: 50.6481, lng: 20.3019, wiki: "Jędrzejów" },
      { kod: "TKA", nazwa: "Kazimierza Wielka", typ: "ziemski", woj: "świętokrzyskie", lat: 50.2675, lng: 20.4942, wiki: "Kazimierza_Wielka" },
      { kod: "TKI", nazwa: "Kielce (powiat)", typ: "ziemski", woj: "świętokrzyskie", lat: 50.8500, lng: 20.6500, wiki: "Powiat_kielecki" },
      { kod: "TKN", nazwa: "Końskie", typ: "ziemski", woj: "świętokrzyskie", lat: 51.1908, lng: 20.4067, wiki: "Końskie" }, // Fixed TKO to TKN
      { kod: "TOP", nazwa: "Opatów", typ: "ziemski", woj: "świętokrzyskie", lat: 50.8042, lng: 21.4286, wiki: "Opatów" },
      { kod: "TOS", nazwa: "Ostrowiec Świętokrzyski", typ: "ziemski", woj: "świętokrzyskie", lat: 50.9292, lng: 21.3858, wiki: "Ostrowiec_Świętokrzyski" },
      { kod: "TPI", nazwa: "Pińczów", typ: "ziemski", woj: "świętokrzyskie", lat: 50.5217, lng: 20.5256, wiki: "Pińczów" },
      { kod: "TSA", nazwa: "Sandomierz", typ: "ziemski", woj: "świętokrzyskie", lat: 50.6822, lng: 21.7494, wiki: "Sandomierz" },
      { kod: "TSK", nazwa: "Skarżysko-Kamienna", typ: "ziemski", woj: "świętokrzyskie", lat: 51.1106, lng: 20.8728, wiki: "Skarżysko-Kamienna" },
      { kod: "TST", nazwa: "Starachowice", typ: "ziemski", woj: "świętokrzyskie", lat: 51.0383, lng: 21.0728, wiki: "Starachowice" },
      { kod: "TSZ", nazwa: "Staszów", typ: "ziemski", woj: "świętokrzyskie", lat: 50.5594, lng: 21.1672, wiki: "Staszów" },
      { kod: "TLW", nazwa: "Włoszczowa", typ: "ziemski", woj: "świętokrzyskie", lat: 50.8511, lng: 19.9697, wiki: "Włoszczowa" },

      // ========== WARMIŃSKO-MAZURSKIE (N) ==========
      { kod: "NO", nazwa: "Olsztyn", typ: "miasto", woj: "warmińsko-mazurskie", lat: 53.7784, lng: 20.4801, wiki: "Olsztyn" },
      { kod: "NE", nazwa: "Elbląg", typ: "miasto", woj: "warmińsko-mazurskie", lat: 54.1522, lng: 19.4088, wiki: "Elbląg" },
      { kod: "NBA", nazwa: "Bartoszyce", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.2519, lng: 20.8064, wiki: "Bartoszyce" },
      { kod: "NBR", nazwa: "Braniewo", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.3792, lng: 19.8225, wiki: "Braniewo" },
      { kod: "NDZ", nazwa: "Działdowo", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.2369, lng: 20.1789, wiki: "Działdowo" },
      { kod: "NEB", nazwa: "Elbląg (powiat)", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.1500, lng: 19.4500, wiki: "Powiat_elbląski" },
      { kod: "NEL", nazwa: "Ełk", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.8278, lng: 22.3625, wiki: "Ełk" },
      { kod: "NGI", nazwa: "Giżycko", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.0381, lng: 21.7644, wiki: "Giżycko" },
      { kod: "NGO", nazwa: "Gołdap", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.3092, lng: 22.3050, wiki: "Gołdap" },
      { kod: "NIL", nazwa: "Iława", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.5928, lng: 19.5681, wiki: "Iława" },
      { kod: "NKE", nazwa: "Kętrzyn", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.0769, lng: 21.3719, wiki: "Kętrzyn" },
      { kod: "NLI", nazwa: "Lidzbark Warmiński", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.1264, lng: 20.5775, wiki: "Lidzbark_Warmiński" },
      { kod: "NMR", nazwa: "Mrągowo", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.8697, lng: 21.3050, wiki: "Mrągowo" },
      { kod: "NNI", nazwa: "Nidzica", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.3592, lng: 20.4264, wiki: "Nidzica" },
      { kod: "NNM", nazwa: "Nowe Miasto Lubawskie", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.4250, lng: 19.5933, wiki: "Nowe_Miasto_Lubawskie" },
      { kod: "NOL", nazwa: "Olsztyn (powiat)", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.7800, lng: 20.4800, wiki: "Powiat_olsztyński" },
      { kod: "NOE", nazwa: "Olecko", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.0397, lng: 22.5028, wiki: "Olecko" },
      { kod: "NOS", nazwa: "Ostróda", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.6975, lng: 19.9694, wiki: "Ostróda" },
      { kod: "NPI", nazwa: "Pisz", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.6258, lng: 21.8081, wiki: "Pisz" },
      { kod: "NSZ", nazwa: "Szczytno", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 53.5614, lng: 20.9844, wiki: "Szczytno" },
      { kod: "NWE", nazwa: "Węgorzewo", typ: "ziemski", woj: "warmińsko-mazurskie", lat: 54.2111, lng: 21.7456, wiki: "Węgorzewo" },

      // ========== WIELKOPOLSKIE (P) ==========
      { kod: "PO", nazwa: "Poznań", typ: "miasto", woj: "wielkopolskie", lat: 52.4064, lng: 16.9252, wiki: "Poznań" },
      { kod: "PK", nazwa: "Kalisz", typ: "miasto", woj: "wielkopolskie", lat: 51.7575, lng: 18.0900, wiki: "Kalisz" },
      { kod: "PKO", nazwa: "Konin", typ: "miasto", woj: "wielkopolskie", lat: 52.2231, lng: 18.2511, wiki: "Konin" },
      { kod: "PL", nazwa: "Leszno", typ: "miasto", woj: "wielkopolskie", lat: 51.8403, lng: 16.5750, wiki: "Leszno" },
      { kod: "PCH", nazwa: "Chodzież", typ: "ziemski", woj: "wielkopolskie", lat: 52.9947, lng: 16.9189, wiki: "Chodzież" },
      { kod: "PCT", nazwa: "Czarnków-Trzcianka", typ: "ziemski", woj: "wielkopolskie", lat: 52.9036, lng: 16.5683, wiki: "Powiat_czarnkowsko-trzcianecki" }, // Fixed PCZ to PCT
      { kod: "PGN", nazwa: "Gniezno", typ: "ziemski", woj: "wielkopolskie", lat: 52.5347, lng: 17.5961, wiki: "Gniezno" },
      { kod: "PGS", nazwa: "Gostyń", typ: "ziemski", woj: "wielkopolskie", lat: 51.8825, lng: 17.0119, wiki: "Gostyń" },
      { kod: "PGO", nazwa: "Grodzisk Wielkopolski", typ: "ziemski", woj: "wielkopolskie", lat: 52.2381, lng: 16.3547, wiki: "Grodzisk_Wielkopolski" },
      { kod: "PJA", nazwa: "Jarocin", typ: "ziemski", woj: "wielkopolskie", lat: 51.9700, lng: 17.5044, wiki: "Jarocin" },
      { kod: "PKA", nazwa: "Kalisz (powiat)", typ: "ziemski", woj: "wielkopolskie", lat: 51.7600, lng: 18.0500, wiki: "Powiat_kaliski" },
      { kod: "PKE", nazwa: "Kępno", typ: "ziemski", woj: "wielkopolskie", lat: 51.2806, lng: 17.9897, wiki: "Kępno" },
      { kod: "PKL", nazwa: "Koło", typ: "ziemski", woj: "wielkopolskie", lat: 52.2014, lng: 18.6394, wiki: "Koło_(miasto)" },
      { kod: "PKN", nazwa: "Konin (powiat)", typ: "ziemski", woj: "wielkopolskie", lat: 52.2200, lng: 18.2500, wiki: "Powiat_koniński" },
      { kod: "PKS", nazwa: "Kościan", typ: "ziemski", woj: "wielkopolskie", lat: 52.0856, lng: 16.6431, wiki: "Kościan" },
      { kod: "PKR", nazwa: "Krotoszyn", typ: "ziemski", woj: "wielkopolskie", lat: 51.6986, lng: 17.4406, wiki: "Krotoszyn" },
      { kod: "PLE", nazwa: "Leszno (powiat)", typ: "ziemski", woj: "wielkopolskie", lat: 51.8500, lng: 16.5500, wiki: "Powiat_leszczyński" },
      { kod: "PMI", nazwa: "Międzychód", typ: "ziemski", woj: "wielkopolskie", lat: 52.5917, lng: 15.8736, wiki: "Międzychód" },
      { kod: "PNT", nazwa: "Nowy Tomyśl", typ: "ziemski", woj: "wielkopolskie", lat: 52.3217, lng: 16.1278, wiki: "Nowy_Tomyśl" },
      { kod: "POB", nazwa: "Oborniki", typ: "ziemski", woj: "wielkopolskie", lat: 52.6469, lng: 16.8131, wiki: "Oborniki" },
      { kod: "POS", nazwa: "Ostrów Wielkopolski", typ: "ziemski", woj: "wielkopolskie", lat: 51.6500, lng: 17.8081, wiki: "Ostrów_Wielkopolski" },
      { kod: "POT", nazwa: "Ostrzeszów", typ: "ziemski", woj: "wielkopolskie", lat: 51.4264, lng: 17.9381, wiki: "Ostrzeszów" },
      { kod: "PP", nazwa: "Piła", typ: "ziemski", woj: "wielkopolskie", lat: 53.1511, lng: 16.7383, wiki: "Piła" }, // Fixed PPI to PP
      { kod: "PPL", nazwa: "Pleszew", typ: "ziemski", woj: "wielkopolskie", lat: 51.8939, lng: 17.7894, wiki: "Pleszew" },
      { kod: "POZ", nazwa: "Poznań (powiat)", typ: "ziemski", woj: "wielkopolskie", lat: 52.4000, lng: 16.9000, wiki: "Powiat_poznański" }, // Fixed PP to POZ
      { kod: "PRA", nazwa: "Rawicz", typ: "ziemski", woj: "wielkopolskie", lat: 51.6097, lng: 16.8589, wiki: "Rawicz" },
      { kod: "PSL", nazwa: "Słupca", typ: "ziemski", woj: "wielkopolskie", lat: 52.2856, lng: 17.8717, wiki: "Słupca" },
      { kod: "PSZ", nazwa: "Szamotuły", typ: "ziemski", woj: "wielkopolskie", lat: 52.6125, lng: 16.5764, wiki: "Szamotuły" }, // Fixed PSE to PSZ
      { kod: "PSR", nazwa: "Środa Wielkopolska", typ: "ziemski", woj: "wielkopolskie", lat: 52.2289, lng: 17.2792, wiki: "Środa_Wielkopolska" },
      { kod: "PSE", nazwa: "Śrem", typ: "ziemski", woj: "wielkopolskie", lat: 52.0894, lng: 17.0144, wiki: "Śrem" }, // Fixed PSD to PSE
      { kod: "PTU", nazwa: "Turek", typ: "ziemski", woj: "wielkopolskie", lat: 52.0142, lng: 18.5006, wiki: "Turek_(miasto)" },
      { kod: "PWA", nazwa: "Wągrowiec", typ: "ziemski", woj: "wielkopolskie", lat: 52.8081, lng: 17.2014, wiki: "Wągrowiec" },
      { kod: "PWL", nazwa: "Wolsztyn", typ: "ziemski", woj: "wielkopolskie", lat: 52.1108, lng: 16.1117, wiki: "Wolsztyn" }, // Fixed PWO to PWL
      { kod: "PW", nazwa: "Września", typ: "ziemski", woj: "wielkopolskie", lat: 52.3247, lng: 17.5675, wiki: "Września" }, // Fixed PWR to PW
      { kod: "PZL", nazwa: "Złotów", typ: "ziemski", woj: "wielkopolskie", lat: 53.3636, lng: 17.0339, wiki: "Złotów" },

      // ========== ZACHODNIOPOMORSKIE (Z) ==========
      { kod: "ZS", nazwa: "Szczecin", typ: "miasto", woj: "zachodniopomorskie", lat: 53.4285, lng: 14.5528, wiki: "Szczecin" },
      { kod: "ZK", nazwa: "Koszalin", typ: "miasto", woj: "zachodniopomorskie", lat: 54.1944, lng: 16.1722, wiki: "Koszalin" },
      { kod: "ZSW", nazwa: "Świnoujście", typ: "miasto", woj: "zachodniopomorskie", lat: 53.9097, lng: 14.2475, wiki: "Świnoujście" },
      { kod: "ZBI", nazwa: "Białogard", typ: "ziemski", woj: "zachodniopomorskie", lat: 54.0064, lng: 15.9881, wiki: "Białogard" },
      { kod: "ZCH", nazwa: "Choszczno", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.1683, lng: 15.4203, wiki: "Choszczno" },
      { kod: "ZDR", nazwa: "Drawsko Pomorskie", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.5253, lng: 15.8108, wiki: "Drawsko_Pomorskie" },
      { kod: "ZGL", nazwa: "Goleniów", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.5658, lng: 14.8275, wiki: "Goleniów" },
      { kod: "ZGY", nazwa: "Gryfice", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.9158, lng: 15.2031, wiki: "Gryfice" },
      { kod: "ZGR", nazwa: "Gryfino", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.2522, lng: 14.4878, wiki: "Gryfino" },
      { kod: "ZKA", nazwa: "Kamień Pomorski", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.9694, lng: 14.7681, wiki: "Kamień_Pomorski" },
      { kod: "ZKL", nazwa: "Kołobrzeg", typ: "ziemski", woj: "zachodniopomorskie", lat: 54.1758, lng: 15.5836, wiki: "Kołobrzeg" },
      { kod: "ZKO", nazwa: "Koszalin (powiat)", typ: "ziemski", woj: "zachodniopomorskie", lat: 54.1900, lng: 16.1700, wiki: "Powiat_koszaliński" },
      { kod: "ZLO", nazwa: "Łobez", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.6394, lng: 15.6228, wiki: "Łobez" },
      { kod: "ZMY", nazwa: "Myślibórz", typ: "ziemski", woj: "zachodniopomorskie", lat: 52.9258, lng: 14.8689, wiki: "Myślibórz" },
      { kod: "ZPL", nazwa: "Police", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.5497, lng: 14.5722, wiki: "Police_(miasto)" },
      { kod: "ZPY", nazwa: "Pyrzyce", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.1497, lng: 14.8911, wiki: "Pyrzyce" },
      { kod: "ZSL", nazwa: "Sławno", typ: "ziemski", woj: "zachodniopomorskie", lat: 54.3625, lng: 16.6789, wiki: "Sławno" },
      { kod: "ZSZ", nazwa: "Szczecin (powiat - Szczecinek)", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.7100, lng: 16.6986, wiki: "Szczecinek" },
      { kod: "ZST", nazwa: "Stargard", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.3367, lng: 15.0500, wiki: "Stargard" },
      { kod: "ZSD", nazwa: "Świdwin", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.7733, lng: 15.7728, wiki: "Świdwin" },
      { kod: "ZWA", nazwa: "Wałcz", typ: "ziemski", woj: "zachodniopomorskie", lat: 53.2722, lng: 16.4711, wiki: "Wałcz" }
];
